---
input_frames_folder_path: ./- frames
output_videos_folder_path: ./- video
legend_images_folder_path: ./- legend images

margin: # Margin in pixels for any text overlay
  x: 30
  y: 30

char_width_by_font: 0.6 # Ratio of 1 character width to the font size (e.g., 0.5 means 50% of the font size)
line_height_by_font: 1 # Ratio of line height to the font size (e.g., 1 means 100% of the font size)

timer_text_style:
  font_size: 24
  font_family: Monospac821 BT
  color: white
  shadow: false

title_text_style:
  font_size: 28
  font_family: Sans
  color: white
  shadow: false

# Generate a video for each map in this list
maps:
- name: Antonia 29-09-24 15.30 al 17-11-24 # Map name must be the folder name with ALL the frames, and will be the name of the video to be generated
  frame_name: fa%04d.png # Frame name pattern (%04d works with 5 digits or more if pass from 9999). This is changed in QGIS when generating the frames.
  framerate: 6 # Frames per Second

  # Path to the legend image to overlay over the video
  overlay_legend_path: Leyenda 1 cabra Centro.png

  # Optional title text to be displayed on the video
  title:
    text: 
    position: top_left # Position of the title text on the video (top_left, top_right, bot_left, bot_right)

  # Timer configuration (writes something like '05-08-2024 07:35' over the video)
  timer: # Timer configuration (like 05-08-2024 07:35)
    realtime_date: false # If false, show the days passed since the initial date if 30/31 days month is not working well
    show_date: true # If false, only show the time
    show_start_and_end_date: true
    interval: 5m # Interval for each frame (1M = 1 month, 1d = 1 day, 1h = 1 hour, 1m = 1 minute, 1s = 1 second)
    initial_datetime: 29-09-2024 15:30:00 # Initial date and time for the timer
    end_datetime: 17-11-2024 23:59:59 # End date and time for the timer (not necessary if realtime_date is true)
    
    position: bot_right # Position of the timer text on the video (top_left, top_right, bot_left, bot_right)
